env: "local"

http_server:
  address: "localhost:8085"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s
db:
  host: "localhost"
  port: 5432
  name: "database_orders"
  user: "root"
  password: "root_password"
  ssl_mode: "disable"
